### ISSUE TITLE
TEMPLATE: Add progress emoji within module for 100% completion

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-pipeline#34]
Send a completed progress emoji (✅✅✅✅) with congratulations.msg_list in the module flow.

**Comment by fagiothree** [comment]
modified progress_tracker_template https://docs.google.com/spreadsheets/d/1hcH8pFdiHZN0UvZgyv3Zht9ARBTx-VXhNBI2o8L7fHU/edit#gid=1842648522 accordingly
