### ISSUE TITLE
FLOW EDITING: Improve child name replacement

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-pipeline#38]
In https://docs.google.com/spreadsheets/d/1i_oqiJYkeoMsYdeFOcKlvvjnNCEdQnZlsm17fgNvK0s/edit#gid=0 the edits defined in "insert-childname" replace Your Child with @fields.child_nickname or "your child" .
This doesn't work when Your Child is at the beginning of the sentence because it should be replaced by "Your child".
We would need to replace the current regex to cover the different cases
![image](https://github.com/IDEMSInternational/parenttext-pipeline/assets/32491856/d5dfaa93-98a9-49ca-9d3d-fb6ffa677a79)

**Comment by istride** [comment]
To also match the case where "Your Child" appears after a full stop, use the pattern `(^|.*\. )Your Child.*`. For example:

```
# Before
Your Child something
Something. Your Child something

# After
Your child something
Something. Your child something
```

**Comment by istride** [comment]
To match "Your Child" after question and punctuation marks too.

```
(^|.*[\.?!] )Your Child.*
```
