### ISSUE TITLE
CODE: include warning file for overrides from rpft in output

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-pipeline#61]
https://github.com/IDEMSInternational/rapidpro-flow-toolkit/pull/107 produces (? to double check) a log file with warnings related to overrides and duplicate sheets. The file should also be produced when running the pipeline

**Comment by istride** [comment]
I have made a [change](https://github.com/IDEMSInternational/parenttext-pipeline/commit/5871544ccbb966e10c925f394c82d9c84fc4623e) to the pipeline that will initialise the Toolkit logger. This means that a log file with warnings and errors will be created at 'output/rpft.log'.

**Comment by istride** [comment]
Just make sure you are using the latest version of the Toolkit and Pipeline.
