### ISSUE TITLE
Revise Menu Structure

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-pipeline#84]
Based on feedback from users in Malaysia, there is a request to simplify the main menu navigation. In the approved revised navigation, three menu options (track my progress, review completed lesson, troubleshooting) are renamed for clarity and clustered together under a parent menu option titled, "Review and Track My Progress." Other menu options have been renamed (noted with an asterisk) for clarity based on user feedback. 

<img width="717" alt="image" src="https://github.com/IDEMSInternational/parenttext-pipeline/assets/74552270/1ff19c30-258d-44d2-bb22-54bc54ba4313">

**Comment by fagiothree** [comment]
Should there be an option for LTP activities as well?

**Comment by lauriemarkle** [comment]
Let's go without it for now. Can add it back in later if there's a need, but parents are getting prompted for activities at the end of each daily interaction.

**Comment by fagiothree** [comment]
Corresponding data list implemented in https://docs.google.com/spreadsheets/d/1lwmMa18SM7bUR-og__daYgDNlEfwnj-KtLjC7Cw-EHo/edit#gid=365544105 (global) and in https://docs.google.com/spreadsheets/d/1yUzKndclwMurTwBgDTzA5ha7xLjj214oZy10KYtjW4U/edit#gid=1325741911 for Mexico to replace ParentText with Crianza de Consciencia+
